import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CursorEffect from "@/CursorEffects";
import SmoothScroll from "@/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll />
        <div className="cursor" id="cursor"></div>
        <div className="cursor-follower" id="follower"></div>
        <CursorEffect />
        {children}
      </body>
    </html>
  );
}
